version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80" 
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080" 
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/data:/app/data

